### PR TITLE
Add constellation information to the timerboard.

### PR DESCRIPTION
**Pull request by lordcheeto**
The current sovereignty system in Eve Online, FozzieSov, operates on the level of constellations. Adding this information to the tool will allow users to filter on the constellation, providing a more concise display of timers relevant to their strategic operation.

### CODE REVIEW

**Comment by lordcheeto** [comment]
This pull request would close issue #3.

**Comment by jordillo** [comment]
an add'l constellation filter works great if you only hold one or 2 constellations. however, a filter is not a replacement for adding a 'constellation' column to the page. when holding several constellations with multiple reinforced systems, i want to be able to see everything at a glance.

**Comment by lordcheeto** [comment]
@jordillo To be clear, this does add a constellation column. The filter matches anywhere in the row, even the time or defender score.

**Comment by jordillo** [comment]
sweet!  :-)  thanks for the clarification.

**Pull request closed without merging**
